# BEGIN: 8zv7t5r2n6p1
name: generate-sdrdm-api
description: |
  "This action generates the sdRDM API from an sdRDM schema."
inputs:
  library_name:
    description: "The name of the library to be generated."
    required: true
    default: "unstable"
  schema_path:
    description: "Path to the sdRDM schema."
    required: true
    default: "./specifcations/"
  out_dir:
    description: "Target directory for the generated API."
    required: true
    default: "./"
  branch:
    description: "The sdRDM branch to be used for the generated API."
    required: true
    default: "linking-refactor"
  push:
    description: "Push the generated API to the specified branch."
    required: true
    default: "true"
  schema_out_dir:
    description: "Target directory for the generated schema."
    required: true
    default: "./"
  schema:
    description: "Generate the sdRDM schema."
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Install Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.11"
    - name: "Generating API"
      shell: "bash"
      run: |
        printf "::group::🔧 Installing dependencies\n"

        python -m pip install git+https://github.com/JR-1991/software-driven-rdm.git@${{ inputs.branch }}

        printf "::endgroup::\n"

        printf "::group::🤖 Generating sdRDM API\n"
        
        sdrdm generate \
          --path "${{ inputs.schema_path }}" \
          --out "${{ inputs.out_dir }}" \
          --name "${{ inputs.library_name }}"

        printf "::endgroup::\n"

        if [[ ${{ inputs.schema }} == 'true' ]]; then
          printf "::group::🤖 Generating sdRDM schema\n"
          
          sdrdm schema \
            --path "${{ inputs.schema_path }}" \
            --out "${{ inputs.schema_out_dir }}" \
            --name "${{ inputs.library_name }}" \
            --url "${{ github.server_url }}/${{ github.repository }}"
            --commit "${{ github.sha }}"

          printf "::endgroup::\n"
        fi
    - name: "Pushing API"
      if: ${{ inputs.push == 'true' }}
      shell: "bash"
      run: |
        if [[ `git status --porcelain` ]]; then
            git add --all
            git config --global user.name 'sdRDM Bot'
            git config --global user.email 'sdRDM@bot.com'
            git commit -am "API update"
            git push
        else
          echo "Nothing changed!"
        fi
