name: Test Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sdRDM library
        uses: ./
        with:
          library_name: "Test"
          schema_path: "./.github/workflows/model.md"
          output_dir: "./.github/workflows/"
          push: "false"
      - name: Test
        run: |
          printf "::group::Testing sdRDM library\n"

          cp ./.github/workflows/test_generated_api.py ./
          
          python -m pip install rich
          python test_generated_api.py

          printf "✅ Done\n"
          printf "::endgroup::"
